services:
  - type: web
    name: magaly-bot
    env: python
    plan: free
    region: oregon
    buildCommand: |
      python --version
      pip install -r requirements.txt
    startCommand: python main.py
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
